version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        depends_on:
            - "php"
        volumes:
            - "$PWD/conf.d:/etc/nginx/conf.d"
            - "$PWD/html:/usr/share/nginx/html"
        container_name: "compose-nginx"
    php:
        image: bitnami/php-fpm:5.6
        ports:
            - "9000:9000"
        volumes:
            - "$PWD/html:/var/www/html"
        container_name: "compose-php"